project_id = "yxdcngazogqmrffllbkl"

[functions.generate-sessions]
verify_jwt = false

[functions.calculate-tuition]
verify_jwt = false

[functions.post-payment]
verify_jwt = false

[functions.calculate-payroll]
verify_jwt = false

[functions.manage-admin-users]
verify_jwt = false

[functions.create-teacher]
verify_jwt = true

[functions.create-family]
verify_jwt = true